version: '3.8'

services:
  streamlit_app:
    build: ./streamlit_app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/generate
    networks:
      - ollama_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama_network

networks:
  ollama_network:
    driver: bridge

volumes:
  ollama_data:
